# Generated by Django 4.2.2 on 2023-06-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sync",
            name="contract_abi",
            field=models.JSONField(default=dict, help_text="ETH Contract ABI", verbose_name="Contract ABI"),
        ),
        migrations.AlterField(
            model_name="sync",
            name="event_names",
            field=models.JSONField(
                default=list, help_text="Array of event names that should be synced", verbose_name="Event names"
            ),
        ),
        migrations.AlterField(
            model_name="sync",
            name="meta",
            field=models.JSONField(
                default=dict,
                help_text='Meta data specific for this sync. Can be used by other modules to customize their behavior for this sync.In periodic task specific sync can be used like this: "{"name": "My Sync Name"}", or using some meta data: "{"meta__network": "goerli"}". Under the hood it will be using Sync.objects.get(**kwargs)',
                verbose_name="Meta data",
            ),
        ),
    ]
