# Generated by Django 4.2.2 on 2023-06-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainnetV4Operator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operatorId", models.IntegerField(verbose_name="Operator ID")),
                ("publicKey", models.TextField(verbose_name="Operator Public Key")),
                ("ownerAddress", models.CharField(max_length=255, verbose_name="Owner Address")),
                ("blockNumber", models.CharField(max_length=255, verbose_name="Block Number")),
                ("transactionIndex", models.IntegerField(verbose_name="Transaction Index")),
                ("fee", models.CharField(max_length=255, verbose_name="Fee")),
                ("previousFee", models.CharField(max_length=255, verbose_name="Previous Fee")),
                ("declaredFee", models.CharField(max_length=255, verbose_name="Declared Fee")),
                ("isValid", models.BooleanField(default=True, verbose_name="Is Valid")),
                ("isDeleted", models.BooleanField(default=False, verbose_name="Is Deleted")),
                ("errors", models.JSONField(blank=True, default=list, verbose_name="Errors")),
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("network", models.CharField(max_length=255, verbose_name="Network")),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestnetV4Operator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operatorId", models.IntegerField(verbose_name="Operator ID")),
                ("publicKey", models.TextField(verbose_name="Operator Public Key")),
                ("ownerAddress", models.CharField(max_length=255, verbose_name="Owner Address")),
                ("blockNumber", models.CharField(max_length=255, verbose_name="Block Number")),
                ("transactionIndex", models.IntegerField(verbose_name="Transaction Index")),
                ("fee", models.CharField(max_length=255, verbose_name="Fee")),
                ("previousFee", models.CharField(max_length=255, verbose_name="Previous Fee")),
                ("declaredFee", models.CharField(max_length=255, verbose_name="Declared Fee")),
                ("isValid", models.BooleanField(default=True, verbose_name="Is Valid")),
                ("isDeleted", models.BooleanField(default=False, verbose_name="Is Deleted")),
                ("errors", models.JSONField(blank=True, default=list, verbose_name="Errors")),
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("network", models.CharField(max_length=255, verbose_name="Network")),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
