# Generated by Django 4.2.2 on 2023-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainnetV4Event",
            fields=[
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("network", models.CharField(max_length=255, verbose_name="Network")),
                ("event", models.CharField(max_length=255, verbose_name="Event name")),
                ("logIndex", models.IntegerField(verbose_name="Log Index")),
                ("transactionIndex", models.IntegerField(verbose_name="Transaction Index")),
                (
                    "transactionHash",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True, verbose_name="Transaction Hash"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("blockHash", models.CharField(max_length=255, verbose_name="Block Hash")),
                ("blockNumber", models.CharField(max_length=255, verbose_name="Block Number")),
                ("args", models.JSONField(verbose_name="Arguments")),
                (
                    "process_status",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, verbose_name="Process Status"
                    ),
                ),
                ("errors", models.JSONField(blank=True, default="", verbose_name="Errors")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MainnetV4Operator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("network", models.CharField(max_length=255, verbose_name="Network")),
                ("operatorId", models.IntegerField(verbose_name="Operator ID")),
                ("transactionIndex", models.IntegerField(verbose_name="Transaction Index")),
                ("ownerAddress", models.CharField(max_length=255, verbose_name="Owner Address")),
                ("blockNumber", models.CharField(max_length=255, verbose_name="Block Number")),
                ("errors", models.JSONField(blank=True, default="", verbose_name="Errors")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestnetV4Event",
            fields=[
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("network", models.CharField(max_length=255, verbose_name="Network")),
                ("event", models.CharField(max_length=255, verbose_name="Event name")),
                ("logIndex", models.IntegerField(verbose_name="Log Index")),
                ("transactionIndex", models.IntegerField(verbose_name="Transaction Index")),
                (
                    "transactionHash",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True, verbose_name="Transaction Hash"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("blockHash", models.CharField(max_length=255, verbose_name="Block Hash")),
                ("blockNumber", models.CharField(max_length=255, verbose_name="Block Number")),
                ("args", models.JSONField(verbose_name="Arguments")),
                (
                    "process_status",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, verbose_name="Process Status"
                    ),
                ),
                ("errors", models.JSONField(blank=True, default="", verbose_name="Errors")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestnetV4Operator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("network", models.CharField(max_length=255, verbose_name="Network")),
                ("operatorId", models.IntegerField(verbose_name="Operator ID")),
                ("transactionIndex", models.IntegerField(verbose_name="Transaction Index")),
                ("ownerAddress", models.CharField(max_length=255, verbose_name="Owner Address")),
                ("blockNumber", models.CharField(max_length=255, verbose_name="Block Number")),
                ("errors", models.JSONField(blank=True, default="", verbose_name="Errors")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
