# Generated by Django 4.2.2 on 2023-06-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssv_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainnetv4event",
            name="errors",
            field=models.JSONField(blank=True, default=list, verbose_name="Errors"),
        ),
        migrations.AlterField(
            model_name="mainnetv4operator",
            name="errors",
            field=models.JSONField(blank=True, default=list, verbose_name="Errors"),
        ),
        migrations.AlterField(
            model_name="testnetv4event",
            name="errors",
            field=models.JSONField(blank=True, default=list, verbose_name="Errors"),
        ),
        migrations.AlterField(
            model_name="testnetv4operator",
            name="errors",
            field=models.JSONField(blank=True, default=list, verbose_name="Errors"),
        ),
    ]
